### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by kariavka** [liqpay/sdk-python#1]
File "/home/myproject/lib/liqpay.py", line 129, in str_to_sign
    return base64.b64encode(hashlib.sha1(str).digest())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 76-81: ordinal not in range(128)

**Comment by wowkin2** [comment]
try to use utf-8 encoding for file "/home/myproject/lib/liqpay.py"
and add following lines at the top of this file:
`#!/usr/bin/env python`
`# -*- coding: utf-8 -*-`
